# Generated by Django 2.2.7 on 2019-11-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('photo_url', models.CharField(max_length=200)),
                ('place_name', models.CharField(max_length=100)),
                ('notes', models.TextField()),
            ],
        ),
    ]
