# Generated by Django 2.2.7 on 2019-11-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='author',
            new_name='owner',
        ),
    ]
